# Generated by Django 5.2.5 on 2025-08-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price', max_digits=10)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, help_text='Original price', max_digits=10, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('image', models.ImageField(upload_to='products/')),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('featured', models.BooleanField(default=False, help_text='Show in "Featured Product"')),
                ('trending', models.BooleanField(default=False, help_text='Show in "Trending"')),
                ('back_to_school', models.BooleanField(default=False, help_text='Show in "Back to School"')),
                ('bulk_offer_text', models.CharField(blank=True, help_text='e.g., "Buy 3 or more @ Rs. 101.20"', max_length=120)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
